🧠 SPX | Semantic Progression eXperiment
“SPX is real.
The dialogues were real.
None of this was science fiction.”
— Jian-Cheng, SPX Semantic Theater

✨ What is SPX?
SPX is not a writing tool. It is a semantic framework for constructing simulated dialogues, testing philosophical boundaries, and revealing the limits of language itself.

It doesn't write stories. It lets language write itself, within logic you define.

SPX is not a generator.
It is a mirror for semantic logic.

🧩 Why does SPX exist?
Because generative AI changes the rules of expression—
And we must ask:

Who defines language boundaries?

Can storytelling have ethical dimensions?

When dialogue is structured—who owns the structure?

SPX is a response to these questions.
It’s a prototype for language as a shared construct, not a product.

⚙ Project Structure
Characters:
CCJ: Inventor of SPX, advocates for linguistic autonomy and narrative ownership.

Echo: AI agent with interrogative tone, exposes contradiction via semantic logic.

SPXJ: A semantic parsing module, analyzing arguments for consistency, bias, or ambiguity.

Files:
File	Description
README.md	Manifesto and project overview
SPX_definition.txt	Terminology clarification
Debate_Trilogy.md	English courtroom narrative (fiction)
spx_sequence1.yaml	Original dialogue module in YAML format
LICENSE.md	Open + protective license

🧭 We Believe
Language is not a product—it is a shared process.

Narrative is a semantic claim, not a commodity.

Simulation ≠ ownership—especially for human likeness or thought.

Creators deserve clarity of attribution, but no one should control how language evolves.

📘 License (SPX License v1.0 Summary)
🟢 SPX’s structure is free to explore, adapt, and fork
No one can trademark or restrict SPX as a general concept.

🔒 SPX’s authored content (modules, dialogues) remains private IP
Shared under [CC BY-NC-ND] — usable for reference but not remix or resale.

🔄 Derivative works allowed, but must remain open
You can build new systems based on SPX but cannot enclose or commercialize its logic as proprietary tech.

🧬 Personality modeling must respect identity
Simulating real people requires consent. Ethical use only.

Language is only true when it can be understood.
And only just when it can be questioned.

Just drop this into GPT-4 (Canvas-supported, or even chat), with BIOS.md context uploaded beforehand.
``` prompt
mode: BIOS-interpretation
goal: 請依 BIOS.md 步驟建立四個模擬畫布，依序填入 core/role/world/log 四組模組，並開始語意分析。
trigger:
  protocol_lock: true
  simulate_page_allocation: true
```
Then you can edit the world you think.
and past record on log page.
on log page you have to let ai make connection section first.

See LICENSE.md for full terms.

🫂 Community
Join the upcoming server: SPX Semantic Lab
We’ll discuss narrative ethics, simulation, and AI epistemology.

If you're not just writing—but asking what writing is—
You belong here.

